spring.application.name=jay-board-admin

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

server.servlet.session.persistent=false

spring.profiles.active=local